name: My First Pipeline
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Inject Secret Token
        run: |
          sed -i "s/GITHUB_TOKEN_PLACEHOLDER/${{ secrets.MY_PERSONAL_TOKEN }}/g" script.js
      - name: Save Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-backup
          path: .
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy Now
        uses: actions/deploy-pages@v4