name: My First Pipeline

# Ye kab chalega? Jab bhi aap 'main' branch mein push karoge
on:
  push:
    branches: ["main"]

# Permission deni padegi taaki GitHub Actions aapki site ko change kar sake
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      # 1. Aapka code machine mein download karna
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Backup banana (Artifact)
      # Isse aapki files safe rahengi
      - name: Save Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-backup
          path: .

      # 3. GitHub Pages ko configure karna
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 4. Files ko upload ke liye bundle karna
      - name: Upload Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # 5. Live deploy karna
      - name: Deploy Now
        uses: actions/deploy-pages@v4
